# Site settings
title: Portfolio
description: Portfolio - Simone Del Grosso
baseurl: ""
url: "https://simonedelgrosso.github.io"

# Build settings
markdown: kramdown
timezone: Europe/Rome
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "it"
    values:
      lang: "it"